### ISSUE TITLE
Ability to include variables in the content

### ISSUE THREAD

**Issue by Stuntlover-TM** [01-Feli/DiscordMessenger-Rust#4]
Currently, I have `.set_content("{}", test.to_string())` but it raises an error saying `expected 1 arguement, supplied 2`,  is there any way to fix this without a new update? Thanks in advance.

**Comment by negrifelipe** [comment]
Hi, try using format!("{}", tes) and convert that returns a str. Convert to string and it should work.

**Comment by Stuntlover-TM** [comment]
Hey, where would I put the format! line? Sorry I'm very new to Rust :smile:

**Comment by negrifelipe** [comment]
Hi, try using `.set_content(format!("{}", test));`

**Comment by Stuntlover-TM** [comment]
Thanks, worked!
